plugins {
    id 'com.android.application'
}

android {
    namespace 'com.oke12080.jumprunner'
    compileSdk 35

    defaultConfig {
        applicationId 'com.oke12080.jumprunner'
        minSdk 23
        targetSdk 28
        versionCode 1
        versionName '1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.12.1'
}
